// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbGnsQW6rxeAVJvrbx2mRNagVGtjx9uK4',
    appId: '1:81841259945:web:e2f9eb85de8ee923c8b0b8',
    messagingSenderId: '81841259945',
    projectId: 'camshare-8235f',
    authDomain: 'camshare-8235f.firebaseapp.com',
    storageBucket: 'camshare-8235f.firebasestorage.app',
    measurementId: 'G-B1FSZNJFQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkb2ZrOq-cNdv53XY6RBAyskrOWvzhK5w',
    appId: '1:81841259945:android:61dbff072a5f7596c8b0b8',
    messagingSenderId: '81841259945',
    projectId: 'camshare-8235f',
    storageBucket: 'camshare-8235f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgiPEKVJwrDlnLwGG44IuqYykdWc0InC0',
    appId: '1:81841259945:ios:21417a8f86957c06c8b0b8',
    messagingSenderId: '81841259945',
    projectId: 'camshare-8235f',
    storageBucket: 'camshare-8235f.firebasestorage.app',
    iosBundleId: 'com.example.camShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgiPEKVJwrDlnLwGG44IuqYykdWc0InC0',
    appId: '1:81841259945:ios:21417a8f86957c06c8b0b8',
    messagingSenderId: '81841259945',
    projectId: 'camshare-8235f',
    storageBucket: 'camshare-8235f.firebasestorage.app',
    iosBundleId: 'com.example.camShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbGnsQW6rxeAVJvrbx2mRNagVGtjx9uK4',
    appId: '1:81841259945:web:d6302fcf924b020fc8b0b8',
    messagingSenderId: '81841259945',
    projectId: 'camshare-8235f',
    authDomain: 'camshare-8235f.firebaseapp.com',
    storageBucket: 'camshare-8235f.firebasestorage.app',
    measurementId: 'G-4FXR5GPQ25',
  );
}
